# Generated by Django 5.2 on 2025-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchParameter',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('min_stock_level', models.IntegerField()),
                ('reorder_quantity', models.IntegerField()),
                ('reorder_interval_days', models.IntegerField()),
            ],
            options={
                'db_table': 'dispatch_parameters',
            },
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('part_type', models.CharField(max_length=100)),
                ('used_in_models', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('blocked_parts', models.CharField(blank=True, max_length=100, null=True)),
                ('successor_parts', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_master',
            },
        ),
        migrations.CreateModel(
            name='MaterialOrder',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_id', models.CharField(max_length=100)),
                ('quantity_ordered', models.IntegerField()),
                ('order_date', models.CharField(max_length=100)),
                ('expected_delivery_date', models.CharField(max_length=100)),
                ('supplier_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('actual_delivered_at', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'material_orders',
            },
        ),
        migrations.CreateModel(
            name='S1V1BOM',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'S1_V1_BOM',
            },
        ),
        migrations.CreateModel(
            name='S1V2BOM',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'S1_V2_BOM',
            },
        ),
        migrations.CreateModel(
            name='S2V1BOM',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'S2_V1_BOM',
            },
        ),
        migrations.CreateModel(
            name='S2V2BOM',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'S2_V2_BOM',
            },
        ),
        migrations.CreateModel(
            name='S3V1BOM',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'S3_V1_BOM',
            },
        ),
        migrations.CreateModel(
            name='S3V2BOM',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'S3_V2_BOM',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('sales_order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('order_type', models.CharField(max_length=100)),
                ('requested_date', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('accepted_request_date', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sales_orders',
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('part_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('quantity_available', models.IntegerField()),
            ],
            options={
                'db_table': 'stock_levels',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('part_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=100)),
                ('part_id', models.CharField(max_length=100)),
                ('price_per_unit', models.FloatField()),
                ('lead_time_days', models.IntegerField()),
                ('min_order_qty', models.IntegerField()),
                ('reliability_rating', models.FloatField()),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
