# Generated by Django 5.2 on 2025-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmaster',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
