# Generated by Django 5.2 on 2025-04-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_materialmaster_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sales_order_id',
            field=models.CharField(max_length=100),
        ),
    ]
