# Generated by Django 5.2 on 2025-04-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_salesorder_id_alter_salesorder_sales_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='actual_delivered_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
