# Generated by Django 5.2 on 2025-04-27 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailMessage",
            new_name="Message",
        ),
        migrations.RenameModel(
            old_name="EmailThread",
            new_name="Thread",
        ),
    ]
