# Generated by Django 5.2 on 2025-04-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0002_rename_emailmessage_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="thread_id",
            field=models.CharField(max_length=255),
        ),
    ]
