# Generated by Django 5.2 on 2025-04-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0003_alter_thread_thread_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="thread_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
